version: '3'
services:
  db:
    image: mysql:latest
    container_name: memos_db
    networks:
      - memos_network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: memos_prod
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  memos:
    image: memos:latest
    restart: always
    container_name: my_memos
    networks:
      - memos_network
    volumes:
      - memos_cache:/var/opt/memos
    environment:
      - MEMOS_DRIVER=mysql
      - MEMOS_DSN=root:123456@tcp(memos_db)/memos_prod
    ports:
      - 80:5230

volumes:
  db_data:
  memos_cache:

networks:
  memos_network:
    external: true
